### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by bbkr** [arnsholt/Net-ZMQ#7]
Rakudo 2016.03.

```
===SORRY!=== Error while compiling /home/ppabian/.panda-work/1459338650_1/lib/Net/ZMQ/Pollitem.pm
Malformed parameter
at /home/ppabian/.panda-work/1459338650_1/lib/Net/ZMQ/Pollitem.pm:12
------> od BUILD(Net::ZMQ::Socket :$socket, :$in⏏ as Bool, :$out as Bool, :$err as Bool)
    expecting any of:
        constraint
```

Is that the old form of type cast, which was replaced by `(Bool() :$in)` later?

**Comment by jonathanstowe** [comment]
Hi,
the #9 will fix that as well as the problems with the nativecall types.

**Comment by azawawi** [comment]
@bbkr Thanks for reporting it. 💯 / 💯 
@jonathanstowe  Thanks for fixing it 🥇 👍 
@timo Thanks for merging it 👍 

Closing issue
